packages:
  - '.'
nodeLinker: hoisted
overrides:
  'fast-uri@>=3.0.0 <3.1.6': 3.1.6
  'js-yaml@>=3.0.0 <4.0.0': 3.15.2
  'serialize-javascript@<7.0.5': 7.0.5
  'colord@<2.9.4': 2.9.4
  'sharp@<0.35.4': 0.35.4
  'svgo@>=1.0.0 <3.0.0': 2.8.4
  'svgo@>=4.0.0 <4.1.0': 4.1.0
allowBuilds:
  esbuild: true
  workerd: true
